export const StaticApi = {
  signin: "/authentication/loginUser",
  signup: "/authentication/createNewUser",

  getAllProductCategory: "/productcategory/getAllProductCategory",
  getAllActivateProduct: "/product/getAllActivateProduct",
  getProductByProductCode: "/product/getProductByProductCode",
  searchProducts: "/product/searchProduct",
  addWishlist: "/wishlist/addWishlist",
  removeFromWishlist: "/wishlist/remove",
  getUserWishlist: "/wishlist/user",
  removeFromCart: "/cart/removeFromCart",
  removeProductFromCart: "/cart/removeProductFromCart",
  addToCart: "/cart/addToCart",
  getUserCart: "/cart/getCartItems",
  getAllAddressesOfUser: "/user/address/getAllAddressesOfUser",
  createAddress: "/user/address/createAddress",
  updateAddress: "/user/address/updateAddress",
  deleteAddress: "/user/address/deleteAddress",
  setDefaultAddress: "/user/address/setDefaultAddress",
  placeOrder: "/order/placeOrder",
  getMyOrders: "/order/user-orders",
  directOrder: "/order/direct-order",

};
